module.exports = {
  other: [
    "Car Wash Electricity Bill",
    "Car Wash Rent",
    "GO Quarterly Rent",
    "Tuckshop Electricity Bill",
    "Tuckshop Rent",
    "Miscellaneous",
  ],

  kitchen: [
    "Guests Dinner/Lunch",
    "Guests Refreshments",
    "Daily Kitchen Expense",
    "Staff Food Allowance-Weekly",
    "Gas Cylinder Refilling",
    "External Mechanics/Labour Food Expenses",
    "Miscellaneous",
  ],

  general: [
    "Bill-Internet",
    "Bill-Newspaper",
    "Bill-PESCO",
    "Bill-PTCL/WiFi",
    "Bill-SNGPL",
    "Fake Currency Note Adjustment",
    "Fuel/CNG Asstt. Manager",
    "Fuel/CNG Manager",
    "Jehanzeb Khan Monthly Expenditure",
    "Khadim Hussain Kids School Fee",
    "KP Dir. of Labour (Weight & Measurement) Annual Fee",
    "Local Purchase & Repair-CCTV",
    "Local Purchase-General",
    "Local Purchase-Premises Fixtures",
    "Petty Cash",
    "Repair-Air Conditioner",
    "Repair-Canopy",
    "Repair-Office Furniture/Equipment",
    "Repair-Premises Structure & Fixtures",
    "Transport Intercity",
    "Transport Local",
    "Miscellaneous",
    "Discount Armed Forces",
    "Package Cash Discount",
  ],

  generatordieselelubecompressor: [
    "Diesel-Generator",
    "Lubricant-Compressor",
    "Lubricant-Generator",
    "Miscellaneous",
  ],

  salary: [
    "Balance Monthly Pay Roll",
    "Salary-Advance",
    "Salary-Monthly",
    "Shahzeb Khan-Allowance",
    "Miscellaneous",
  ],

  premisesrent: [
    "Rent Premises-Bara Road LPG",
    "Rent Premises-Farhan Shagai LPG",
    "Rent Premises-Janib Shah",
    "Rent Premises-Mansehra LPG",
    "Rent Premises-Zareef",
    "Miscellaneous",
  ],

  pettycash: [],

  shahzebkhanallowence: [],

  kgandjaws: [
    "KG & JAWS Dastarkhwan-Dry Ration",
    "KG & JAWS Dastarkhwan-Tandoor Roti",
    "KG & JAWS-Langar Cook Salary",
    "KG & JAWS-Vegetables",
    "KG & JAWS Dastarkhwan-Loader Petrol/Lube",
    "KG & JAWS Dastarkhwan-Loader Repair",
    "Miscellaneous",
  ],

  loansgivenreturnedtostation: [
    "Loan given by Dr. Nasir Khan for Bill etc",
    "Loan given by Papoo Khan for Bill etc",
    "Loan returned to Dr. Nasir Khan for Bill etc",
    "Loan returned to Papoo Khan for Bill etc",
    "Loan Given by A for Bill etc",
    "Loan Returned to A for Bill etc",
    "Personal Loan Taken by Dr. Nasir Khan",
    "Personal Loan Taken by Ejaz Khan",
    "Personal Loan Taken by Nadeem Khan",
    "Personal Loan Taken by Papoo Khan",
    "Miscellaneous",
  ],

  machineryrepair: [
    "Cooling Tower Chemical",
    "Local Purchase Spare Parts-compAir Compressor",
    "Local Purchase Spare Parts-Cooling Tower",
    "Local Purchase Spare Parts-Dispenser",
    "Local Purchase Spare Parts-Generator",
    "Repair CNG Compressor",
    "Repair CNG Compressor-CompAir",
    "Repair CNG Compressor-Morgan",
    "Repair Cooling Tower",
    "Repair Generator",
    "Repair Dispenser",
    "Repair Water Motor Cooling Tower",
    "Testing/Calibration of Dispenser Meter",
    "Testing/Calibration of Gas Meter",
    "Local Purchase Spare Parts-Morgan Compressor",
    "Miscellaneous",
  ],

  loansexpenditurebyakeknknk: [
    "Joint Expenditure/Loan",
    "Monthly Disbursement-Dr. Nasir Khan",
    "Monthly Disbursement-Ejaz Khan",
    "Monthly Disbursement-Nadeem Khan",
    "Monthly Disbursement-Papoo Khan",
    "Rent Premises-Bara Road LPG",
    "Rent Premises-Farhan Shagai LPG",
    "Rent Premises-Mansehra LPG",
    "Waqar Khan Profit Share",
    "F.K-Profit/Loss Share on CNG/LPG (3%/5%)",
    "S.U-Profit/Loss Share on CNG/LPG (1.5%/2.5%)",
    "Miscellaneous",
  ],
};
